# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "proxmox" {
  endpoint  = "https://pve.g8.lo:8006/"
  api_token = var.proxmox_api_token
  insecure  = true
  ssh {
    agent       = false
    username    = "root"
    private_key = file("/Users/gwest/.ssh/id_rsa")
  }
}

variable "proxmox_api_token" {
  type      = string
  sensitive = true
}
